export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'


//===========


export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'
//===========
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'


//===========


export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST'
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

//===========


export const ORDER_APPROVE_REQUEST = 'ORDER_APPROVE_REQUEST'
export const ORDER_APPROVE_SUCCESS = 'ORDER_APPROVE_SUCCESS'
export const ORDER_APPROVE_FAIL = 'ORDER_APPROVE_FAIL'


//===========


export const ORDER_UNAPPROVE_REQUEST = 'ORDER_UNAPPROVE_REQUEST'
export const ORDER_UNAPPROVE_SUCCESS = 'ORDER_UNAPPROVE_SUCCESS'
export const ORDER_UNAPPROVE_FAIL = 'ORDER_UNAPPROVE_FAIL'

//===========


export const GET_ORDER_DASHBOARD_REQUEST = 'GET_ORDER_DASHBOARD_REQUEST'
export const GET_ORDER_DASHBOARD_SUCCESS = 'GET_ORDER_DASHBOARD_SUCCESS'
export const GET_ORDER_DASHBOARD_FAIL = 'GET_ORDER_DASHBOARD_FAIL'

//===========
export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'